version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=dj2.settings
    volumes:
      - .:/app
      - ./media:/app/media

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=djangoqj7b0
      - MYSQL_ROOT_PASSWORD=root
      # Remove these two lines:
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/djangoqj7b0.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: